#cloud-config

package_update: true
package_upgrade: true

packages:
  - apache2
  - php
  - php-mysql
  - mysql-client
  - unzip
  - wget

runcmd:
  - systemctl enable apache2
  - systemctl start apache2
  - cd /tmp
  - wget https://wordpress.org/latest.zip
  - unzip latest.zip
  - cp -r wordpress/* /var/www/html/
  - chown -R www-data:www-data /var/www/html
  - cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
  - sed -i "s/database_name_here/${db_name}/" /var/www/html/wp-config.php
  - sed -i "s/username_here/${db_user}/" /var/www/html/wp-config.php
  - sed -i "s/password_here/${db_pass}/" /var/www/html/wp-config.php
  - sed -i "s/localhost/${db_host}/" /var/www/html/wp-config.php
  - systemctl restart apache2
